server.port=8080

spring.application.name=HMS_Project
spring.datasource.url=jdbc:mysql://localhost:3306/library_seat
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=librarySecretKey123
jwt.expiration=86400000